
#target keycloak host
[keycloak]
keycloak.example.org ansible_connection=local

[all:vars]
# Ansible
ansible_user=<ansible user>
#ansible_password=


#aap gateway
aap_gw_ip=<aap gateway hostname/FQDN>
aap_admin_password=<aap admin user password>


#keycloak host
keycloak_hostname=keycloak.example.org

#keycloak admin and testuser password
admin_password=<password>


