###########################readme
# 1. setup keycloak on target node (become true)
# $ ansible-playbook -i <this inventory> keycloak_setup.yml -K
# 
# 2. configure SAML authentication method on AAP (become false)
# $ ansible-playbook -i inv-host aap_saml_config.yml
###########################


#target keycloak host
[keycloak]
keycloak.example.org ansible_connection=local

[all:vars]
# Ansible
ansible_user=admin
#ansible_password=


#aap gateway
aap_gw_ip=aap27.example.org
aap_admin_password=aap3211!


#keycloak host
keycloak_hostname=keycloak.example.org

#keycloak admin password
admin_password=aap3211!


